name: Runtime
on:
  pull_request:
    branches:
      - v2-alpha
    paths:
      - 'v2/internal/frontend/runtime/**'
jobs:
  rebuild-runtime:
    name: Rebuild the runtime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts

      - name: Install dependencies
        uses: elstudio/actions-js-build/build@v4
        with:
          wdPath: 'v2/internal/frontend/runtime'
          args: install

      - name: Rebuild runtime
        uses: elstudio/actions-js-build/build@v4
        with:
          wdPath: 'v2/internal/frontend/runtime'
          args: run build

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('v2/internal/frontend/runtime/package-lock.json') }}
          restore-keys: npm-

      - name: Commit changes
        uses: elstudio/actions-js-build/commit@v4
        with:
          commitMessage: Rebuild runtime
